name: 'Task permutations [hard]'

on:
  push:
    paths:
      - 'hard/permutations.py'
  workflow_dispatch:

jobs:
  test-permutations:
    name: 'test-permutations'
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pytest
      - run: |
          pytest hard/permutations.py
